### ISSUE TITLE
understand the requirements

### ISSUE THREAD

**Issue by saikoushalg** [saikoushalg/GITAM_MERCH#1]
**learn and understand how various merch stores operate.**

- research about their UI/UX  design.

- prepare the requirements for our project.

- add the features relevant to this project to the task sheet 

- if possible also add tags to the requirements (features) like  #necessary, #goodtohave, #disruptive, #important, etc...

**Comment by Srivasthavi** [comment]
Ok done I'll do it in the evening if that's ok?

**Comment by saikoushalg** [comment]
yeah cool!

**Comment by Tharun-reddy01** [comment]
> **learn and understand how various merch stores operate.**
> 
> * research about their UI/UX  design.
> * prepare the requirements for our project.
> * add the features relevant to this project to the task sheet
> * if possible also add tags to the requirements (features) like  #necessary, #goodtohave, #disruptive, #important, etc...

**Comment by saikoushalg** [comment]
done
